version: "3.9"

services:

  discovery-server:
    build: .
    container_name: mitocode-discovery-server
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8761"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 8761:8761
    networks:
      - mitocode

  config-server:
    build: ../config-server/
    container_name: mitocode-config-server
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9000/product-service/dev"]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      CUSTOM.SERVER.PORT: 9000
      EUREKA.SERVER.HOSTNAME: http://discovery-server:8761/eureka
    networks:
      - mitocode

  product-service:
    build: ../product-service/
    container_name: mitocode-product-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA.SERVER.HOSTNAME: http://discovery-server:8761/eureka
      CONFIG.SERVER.HOSTNAME: http://config-server:9000
      MONGODB.URL.CONNECTION: mongodb://mitocode:mitocode@mitocode-mongo-service:27017
      KAFKA.SERVER.HOSTNAME: mitocode-kafka-broker
    networks:
      - mitocode

  cloud-gateway:
    build: ../cloud-gateway/
    container_name: mitocode-cloud-gateway
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 9090:9090
    environment:
      EUREKA.SERVER.HOSTNAME: http://discovery-server:8761/eureka
      CONFIG.SERVER.HOSTNAME: http://config-server:9000
    networks:
      - mitocode

networks:
  mitocode:
    name: mitocode-network